-- ============================================================
-- XXV Congreso Regional Noreste de Medicina Familiar 2026
--
-- Este archivo seedeaba datos de ejemplo (ponentes, conferencias,
-- patrocinadores, una encuesta y un registro de prueba) para probar
-- el sitio antes de tener contenido real. Ese contenido de ejemplo
-- ya fue eliminado de producción intencionalmente — el sitio corre
-- ahora sin datos de muestra, y todo el contenido (ponentes, programa,
-- patrocinadores, etc.) se carga exclusivamente desde el dashboard
-- administrativo (/admin/dashboard).
--
-- Este archivo se deja vacío a propósito para que, si alguien lo
-- vuelve a correr por error, no reinserte contenido de ejemplo.
-- Si en el futuro necesitas datos de prueba para desarrollo local,
-- créalos manualmente desde el dashboard admin o consulta el
-- historial de git de este archivo para recuperar el seed original.
-- ============================================================
